project:
  type: website

website:
  title: "AloeAloe"
  description: "AloeAloe Medical and Scientific Writing Ltd"
  site-url: "aloealoesci.com"
  page-footer: |
    Copyright © AloeAloe Medical and Scientific Writing Ltd
    
    AloeAloe Medical and Scientific Writing Ltd is a company registered in 
    England and Wales (company&nbsp;number:&nbsp;16173550)
    
    Delta 606, Welton Road, Swindon, United Kingdom, SN5 7XF 
  navbar:
    background: $brand-green0
    title: false
    search: false
    left: 
      - text: Home
        href: index.qmd
      - text: Blog
        href: posts.qmd
    right:
      - icon: rss
        href: posts.xml
  favicon: "assets/icon.png"
  twitter-card:
    title: "AloeAloe Medical and Scientific Writing Ltd"
    image: "assets/logo.png"

format:
  html:
    page-layout: full
    theme:
      - brand
      - cosmo
      - styles/styles.scss
    toc: false
    include-in-header:
      text: |
        <script data-goatcounter="https://aloealoe.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
    date-format: DD MMMM YYYY
