project:
  type: website

website:
  title: "AloeAloe"
  description: "AloeAloe Medical and Scientific Writing"
  page-footer: Copyright © 2025, Claire Pike
  navbar:
    search: false
  favicon: "assets/icon.png"
  twitter-card: true

format:
  html:
    theme:
      - brand
      - cosmo
      - styles/styles.scss
    toc: false
