project:
  type: website

website:
  title: "AloeAloe"
  description: "AloeAloe Medical and Scientific Writing Ltd"
  page-footer: |
    Copyright © AloeAloe Medical and Scientific Writing Ltd
    
    AloeAloe Medical and Scientific Writing Ltd is a company registered in 
    England and Wales (company number: 16173550)
    
    Delta 606, Welton Road, Swindon, United Kingdom, SN5 7XF 
  navbar: false
  favicon: "assets/icon.png"
  twitter-card: true

format:
  html:
    theme:
      - brand
      - cosmo
      - styles/styles.scss
    toc: false
    include-in-header:
      text: |
        <script data-goatcounter="https://aloealoe.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
